# Generated by Django 5.1.4 on 2025-03-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='market_cap',
            field=models.CharField(max_length=200),
        ),
    ]
